# Generated by Django 4.1.3 on 2022-12-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('subtitle', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('engine', models.IntegerField()),
                ('numbers_of_tier', models.IntegerField()),
                ('material', models.CharField(max_length=30)),
                ('created_on', models.DateTimeField()),
                ('number_of_sit', models.IntegerField()),
            ],
        ),
    ]
