# Generated by Django 4.1.3 on 2022-12-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=30)),
                ('publication_date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='')),
                ('is_trending', models.BooleanField(verbose_name=True)),
                ('num_pages', models.IntegerField()),
                ('material', models.CharField(max_length=30)),
                ('isbn_number', models.BooleanField()),
                ('book_document', models.CharField(max_length=40)),
            ],
        ),
    ]
