# Generated by Django 4.1.3 on 2022-12-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_book_book_document_alter_book_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn_number',
            field=models.PositiveIntegerField(),
        ),
    ]
