# Generated by Django 4.1.3 on 2022-12-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_book_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='book_img'),
        ),
        migrations.AlterField(
            model_name='book',
            name='material',
            field=models.FileField(blank=True, upload_to='book_docs'),
        ),
    ]
