# Generated by Django 4.1.3 on 2022-12-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_book_image_alter_book_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(blank=True, upload_to='blog_img'),
        ),
    ]
