# Generated by Django 4.1.3 on 2023-01-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_book_book_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='attribute',
            field=models.CharField(blank=True, choices=[('BEST SELLING', 'BEST SELLING'), ('TOP 100', 'TOP 100')], max_length=100),
        ),
    ]
